# Generated by Django 3.2.5 on 2021-08-24 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='active',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
