# Generated by Django 3.2.5 on 2021-09-23 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_orderitem_ordertransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordertransaction',
            name='success',
            field=models.BooleanField(default=False),
        ),
    ]
